manifest:
  self:
    west-commands: scripts/west-commands.yml

  # Override Zephyr's group filter to include nanopb (which is in the optional group)
  group-filter: [-babblesim, +optional]

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: stowood
      url-base: git@github.com:Stowood
      
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0
      import:
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_nxp
          - hal_st
          - fatfs
          - littlefs
          - nanopb

    - name: bfp_common_sw
      remote: stowood
      revision: file_rev_4
      path: bfp_common_sw

