manifest:
  self:
    west-commands: scripts/west-commands.yml

  # Override Zephyr's group filter to include nanopb (which is in the optional group)
  group-filter: [-babblesim, +optional]

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0
      import:
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_nxp
          - hal_st
          - fatfs
          - littlefs
          - nanopb
    - name: bfp_common_sw
      url:  git@github.com:Stowood/bfp_common_sw.git
      revision: proto_rev_5
      path: bfp_common_sw

