#pragma once


enum sensor_attribute_veml6030 {
	SENSOR_ATTR_VEML6030_IT = SENSOR_ATTR_PRIV_START,
    SENSOR_ATTR_VEML6030_GAIN,
	SENSOR_ATTR_VEML6030_PERS,
};

enum sensor_channel_veml6030 {
	SENSOR_CHAN_VEML6030_ALS_RAW_COUNTS = SENSOR_CHAN_PRIV_START,
	SENSOR_CHAN_VEML6030_WHITE_RAW_COUNTS,
};
