/*
 * Generated by simple_img2c.py
 * Header file for test_logo
 */

#ifndef TEST_LOGO_H
#define TEST_LOGO_H

#include <stdint.h>

extern const uint8_t test_logo[];
extern const uint16_t test_logo_width;
extern const uint16_t test_logo_height;
extern const uint32_t test_logo_size;

#define TEST_LOGO_WIDTH test_logo_width
#define TEST_LOGO_HEIGHT test_logo_height
#define TEST_LOGO_SIZE test_logo_size

// RGB565 helper macros
#define RGB565(r,g,b) (((r & 0x1F) << 11) | ((g & 0x3F) << 5) | (b & 0x1F))

#endif /* TEST_LOGO_H */
